// export const GET_NEW_BOOK = "GET_NEW_BOOKS";
// export const GET_HOT_BOOK = "GET_HOT_BOOKS";
// export const GET_RECOMMEND_BOOK = "GET_RECOMMEND_BOOKS";
// export const DISFAVOR = "DISFAVOR";
// export const GET_SWIPER_IMAGES = 'GET_SWIPER_IMAGES';
// export const GET_NAV_ITEMS = 'GET_NAV_ITEMS';

export const GET_FIRST_CATEGROY_LIST = "CATEGROY_LIST";
export const GET_SECOND_CATEGROY_LIST = "GET_SECOND_CATEGROY_LIST";
export const GET_BOOKLIST_BY_CATEGROY = 'GET_BOOKLIST_BY_CATEGROY';
export const GET_BOOKDETAIL_BY_ID = 'GET_BOOKDETAIL_BY_ID';
export const GET_DEMANDDETAIL_BY_ID = 'GET_DEMANDDETAIL_BY_ID';
export const UPLOAD_FILE = 'UPLOAD_FILE';