export default {
  BOOK_LIST: "/pages/book-list/index",
  BOOK_DETAIL: "/pages/book-detail/index",
  DEMAND_DETAIL: "/pages/demand-detail/index",
  SEARCH: "/pages/search/index",
  HOME: "/pages/home/index",
  CATEGORY_LIST: "/pages/category-list/index",
  CATEGORY_CHOOSE: "/pages/category-choose/index",
  MY_PUBLISH: "/pages/my-publish/index",
  MY_COLLECTIONS: "/pages/my-collections/index",
  MINE: "/pages/mine/index",
  INDEX: "/pages/index/index",
  LOGIN: "/pages/login/index",
  CHECK_PHONE: "/pages/check-phone/index",
  SELL_PUBLISH: "/pages/sell-publish/index",
  ORDER_PUBLISH: "/pages/order-publish/index",
  CHECK_ORDER: "/pages/check-order/index",
  BOOK_STORE: "/pages/book-store/index",
  BOOK_CART: "/pages/book-cart/index",
  SUCCESS_PAGE: "/pages/success/index"
};
